# Site settings
title: 'Beauty In Code |Â 2019'
baseurl: ''
url: 'https://beautyincode.se'
permalink: 'pretty'

# Google Analytics tracking code
analytics: 'UA-XXXXXXXX-X'

# Jekyll plugins
plugins:
  - 'jekyll-tidy'

# Server settings
host: 0.0.0.0
port: 5005

# Exclude
exclude:
  - 'CNAME'
  - 'Gemfile'
  - 'Gemfile.lock'
  - 'LICENSE'
  - 'README.md'
  - 'node_modules'
  - 'package.json'
  - 'postcss.*.js'
  - 'script'
  - 'src'
  - 'svg-sprite.config.json'
  - 'vendor'
  - 'yarn.lock'
